---
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
    main: .
    flags:
      - -trimpath
    ldflags: -s -w -X config.Build={{.Date}} -X config.Version={{.Version}}

dockers:
  - image_templates: ["ghcr.io/pipego/{{ .ProjectName }}:{{ .Tag }}-amd64"]
    dockerfile: Dockerfile-goreleaser
    use: docker
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/pipego/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/pipego/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  - name_template: ghcr.io/pipego/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - ghcr.io/pipego/{{ .ProjectName }}:{{ .Tag }}-amd64
  - name_template: ghcr.io/pipego/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/pipego/{{ .ProjectName }}:{{ .Tag }}-amd64

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
