FROM gcr.io/distroless/base-debian11 AS production-stage
WORKDIR /
COPY config.yml /
COPY plugin-fetch /
COPY plugin-filter /
COPY plugin-score /
COPY scheduler /
USER nonroot:nonroot
EXPOSE 28082
CMD ["/scheduler", "--config-file=/config.yml", "--listen-url=:28082"]
